//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newDye.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payements
    {
        public int PayementID { get; set; }
        public Nullable<int> Product { get; set; }
        public Nullable<int> Litre { get; set; }
        public Nullable<int> TotalPrice { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual User User { get; set; }
    }
}
